FROM ubuntu:22.04

EXPOSE 5000-5010/tcp
EXPOSE 5000-5010/udp
SHELL [ "/bin/bash", "-c" ]

RUN apt update
RUN apt install -y lsb-release curl gpg gnupg libicu70

# .NET
WORKDIR /
RUN curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 7.0 --install-dir /.dotnet
ENV DOTNET_ROOT /.dotnet
ENV PATH $PATH:$DOTNET_ROOT:$DOTNET_ROOT/tools

# Hypernex.Networking.Server
ADD ./Networking /opt
WORKDIR /opt
CMD dotnet run --project Hypernex.Networking.Server/Hypernex.Networking.Server.csproj -f net7.0
