networks:
  backend:
    name: Backend
  frontend:
    name: Frontend

services:
  minio-server:
    image: quay.io/minio/minio:latest
    restart: always
    volumes:
      - ./minio_data:/data
    ports:
      - 127.0.0.1:9000:9000
      - 127.0.0.1:9001:9001
    command: server /data --address ":9000" --console-address ":9001"
    networks:
      - backend
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin

  mongodb-server:
    image: mongo:latest
    restart: always
    volumes:
      - ./mongo_data:/data/db
    ports:
      - 127.0.0.1:27017:27017
    networks:
      - backend

  redis-server:
    image: redis:latest
    restart: always
    volumes:
      - ./redis_data:/data
    ports:
      - 127.0.0.1:6379:6379
    networks:
      - backend

  hypernex-api:
    container_name: hypernex-api
    build:
      context: ./
      dockerfile: ./Dockerfile-Api
    healthcheck:
      test: curl -f http://127.0.0.1 || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always
    volumes:
      - ./builds:/opt/API/builds
      - ./configs/config.json:/opt/API/config.json
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:2096:2096
    depends_on:
      - minio-server
      - mongodb-server
      - redis-server
    networks:
      - backend
      - frontend

  hypernex-server:
    container_name: hypernex-server
    build:
      context: ./
      dockerfile: ./Dockerfile-Server
    restart: always
    volumes:
      - ./configs/serverconfig.cfg:/opt/serverconfig.cfg
    ports:
      - 0.0.0.0:5000-5010:5000-5010/tcp
      - 0.0.0.0:5000-5010:5000-5010/udp
    depends_on:
      hypernex-api:
        condition: service_healthy
    networks:
      - frontend
